"""Create access permission table

Revision ID: 8e7c8ac48d6c
Revises: ea4522ff360a
Create Date: 2026-02-28 17:26:27.904298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8e7c8ac48d6c'
down_revision: Union[str, Sequence[str], None] = 'ea4522ff360a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesspermissions',
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('action', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_unique_action_for_token', 'accesspermissions', ['token', 'action'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_action_for_token', table_name='accesspermissions')
    op.drop_table('accesspermissions')
    # ### end Alembic commands ###
